### PR TITLE
fix page iterator bug

### LINKED ISSUE #40: PageIterator repeating same page over and over
I'm using PageIterator to iterate over messages (`/me/messages`). This continues until an error is returned from the `Iterate` function: `Fetching next page failed`

My code:

```go
query := messages.MessagesRequestBuilderGetQueryParameters{
  Select: []string{"body", "sender", "subject"},
}

options := messages.MessagesRequestBuilderGetOptions{
  H: map[string]string{
    "Prefer": "outlook.body-content-type=\"text\"",
  },
  Q: &query,
}

result, err := client.Me().Messages().Get(&options)

if err != nil {
  fmt.Printf("Error getting messages: %v\n", err)
  return
}

pageIterator, err := msgraphcore.NewPageIterator(result, adapter.GraphRequestAdapterBase,
  func() serialization.Parsable {
    return messages.NewMessagesResponse()
  })

if err != nil {
  fmt.Printf("Error creating iterator: %v\n", err)
  return
}

pageIterator.SetHeaders(map[string]string{"Content-Type": "application/json"})

iterateErr := pageIterator.Iterate(func(pageItem interface{}) bool {
  message := pageItem.(graph.Message)
  fmt.Printf("%s\n", *message.GetSubject())
  return true
})

if iterateErr != nil {
  fmt.Printf("Error iterating over messages: %v\n", iterateErr)
  return
}
```

What I've observed from debugging locally is that the `nextLink` is being generated incorrectly. On the first request (the `client.Me().Messages().Get(&options)` call), `nextLink` looks as expected:

```
https://graph.microsoft.com/v1.0/me/messages?%24select=body%2csender%2csubject&%24top=10&%24skip=10
```

But when the iterator requests the next page, it's setting `nextLink` like:

```
https://graph.microsoft.com/v1.0/me/messages?%24%24select=body%2csender%2csubject&%24%24top=10&%24%24skip=10&%24top=10&%24skip=10
```

Notice that:

- The `$` (`%24`) instances are being doubled
- The `skip` and `top` params are repeated, both with the *original* values from the very first `nextLink`, 10 and 10

On subsequent requests it just compounds (3 `$`, `skip`/`top` repeated 3 times, etc.)

### LINKED ISSUE #41: Pausing then attempting to resume doesn't work
Sample of the running code below.  Fails because of this condition in enumerate function. This happens when the pause occurs on the last item of current page. Upon resuming it should fetch the next page but bails because there are no more items in the current page.

```
if pI.pauseIndex >= len(pageItems) {
		return false
	}
```

```
var top int32 = 1

	users, err := client.Users().Get(&users2.UsersRequestBuilderGetOptions{
		Q: &users2.UsersRequestBuilderGetQueryParameters{
			Top: &top,
		},
	})

	if err != nil {
		fmt.Printf("Error getting users information: %v\n", err)
	}

	iterator, err := core.NewPageIterator(users, *adapter, func() abs.Parsable { return users2.NewUsersResponse() })

	if err != nil {
		fmt.Printf("Couldn't create a pageIterator")
	}

	iterator.Iterate(func(pageItem interface{}) bool {
		item := pageItem.(graph.User)
		fmt.Printf("User: %v\n", *item.GetDisplayName())

		if strings.Contains(*item.GetDisplayName(), "Vance") {
			return false
		}
		return true
	})

	iterator.Iterate(func(pageItem interface{}) bool {
		item := pageItem.(graph.User)
		fmt.Printf("Round 2 User: %v\n", *item.GetDisplayName())

		if strings.Contains(*item.GetDisplayName(), "Vance") {
			return false
		}
		return true
	})
```

### PR DESCRIPTION
**Pull request by jobala**
## Overview

Fixes #41 
Fixes #40 

## Demo
N/A

## Notes
N/A

## Testing
* Run `go test`

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
thanks for taking care of this.
can we tackle #40 as part of this PR as well please? (updating the regex)
also, missing changelog entry

**Review by ddyett — APPROVED** [review]
Tested and looks good.

File: graph_odata_query_handler.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ func NewGraphODataQueryHandler() *GraphODataQueryHandler {
 
 // NewGraphODataQueryHandlerWithOptions creates a new instance of GraphODataQueryHandler
 func NewGraphODataQueryHandlerWithOptions(options GraphODataQueryHandlerOptions) *GraphODataQueryHandler {
-	replacementRegexp := "(?i)([^$])(count|deltatoken|expand|filter|format|orderby|search|select|skip|skiptoken|top)="
+	replacementRegexp := "(?i)([^$|$])(count|deltatoken|expand|filter|format|orderby|search|select|skip|skiptoken|top)="
```
Comment (baywet) [inline graph_odata_query_handler.go:50]:
```suggestion
	replacementRegexp := "(?i)([^$|4])(count|deltatoken|expand|filter|format|orderby|search|select|skip|skiptoken|top)="
```

**Review by baywet — CHANGES_REQUESTED** [review]

**Review by baywet — APPROVED** [review]
